### PR TITLE
Reimplement Tide Rider

### PR DESCRIPTION
**Pull request by SpaceNerden**
Sorry for the reverts, accidentally pushed to master. 

There is currently a bug at line 95 where it allows playrs to scale walls. No idea why.

Most of the logic is from Klincraft.

### CODE REVIEW

**Comment by dlee13** [comment]
This will need to be rebased.

**Comment by SpaceNerden** [comment]
Rebased to enchantments?

**Comment by dlee13** [comment]
Yes.

**Comment by SpaceNerden** [comment]
I'm sorry, I tried to rebase it but I could not get my head around the conflicts screen. 
image
None of these are mine, and I can't really understand it.

**Comment by SpaceNerden** [comment]
Made me lose my mind but I made it.

**Comment by dlee13** [comment]
Abilities are supposed to be implemented on enchantments, not items.

**Comment by SpaceNerden** [comment]
Woops. Wil change it.

**Comment by dlee13** [comment]
Wait.

**Comment by dlee13** [comment]
Did a proper rebase, this is how it should've ended up.

**Review by dlee13 — CHANGES_REQUESTED** [review]

**Comment by dlee13** [comment]
Looks good, but that was a scuffed rebase again. I'll fix the rebase and clean up some parts that shouldn't have been touched before merging.

**Review by dlee13 — APPROVED** [review]

**Comment by dlee13** [comment]
Thank you.

**Pull request merged**
