### PR TITLE
Improve commands

### PR DESCRIPTION
**Pull request by TraceLosu**
There is still some stuff that I have not added, such as:
- [X] A stats command for manipulating Minecraft stats of players through commands.
- [X] Collection command not being finalized.
- [X] Use Adventure API for all send messages in MainCommand.

I also have not tested the commits. So for now, it will stay in draft.

### CODE REVIEW

**Comment by dlee13** [comment]
The command feedback feels verbose to me. I think the subcommand formats shouldn't be given when you do the main command. And a subcommand format should instead only be given when you use a subcommand without arguments.

**Comment by TraceLosu** [comment]
> The command feedback feels verbose to me. I think the subcommand formats shouldn't be given when you do the main command. And a subcommand format should instead only be given when you use a subcommand without arguments.

I still think a help page should be given when doing the main command. I'll remove the formats in main command and use hover events to get the description of the command.

**Comment by TraceLosu** [comment]
Everything is finalized. I'll do the last checks in a couple of hours or so.

**Comment by dlee13** [comment]
Will start reviewing in a few hours from now.

**Comment by dlee13** [comment]
There shouldn't be a situation where we'd want to check the stats of a player who hasn't been on the server recently, so I switched `Bukkit#getOfflinePlayer` to `Bukket#getOfflinePlayerIfCached` which won't try making blocking calls to Mojang's auth server.

**Review by dlee13 — APPROVED** [review]

**Review by aurorasmiles — APPROVED** [review]

**Pull request merged**
